// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package gomicro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	CreatedTime          uint64   `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          uint64   `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetCreatedTime() uint64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *User) GetUpdatedTime() uint64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "gomicro.srv.user.user")
	proto.RegisterType((*Error)(nil), "gomicro.srv.user.Error")
	proto.RegisterType((*UserRequest)(nil), "gomicro.srv.user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "gomicro.srv.user.UserResponse")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x4b, 0x85, 0x40,
	0x14, 0x6d, 0x7c, 0xda, 0xc7, 0x35, 0x1e, 0x32, 0x8b, 0x92, 0xa0, 0x10, 0x57, 0x12, 0x64, 0x64,
	0xf4, 0x07, 0x82, 0x88, 0x76, 0x35, 0xd4, 0xa2, 0xa5, 0x39, 0xb7, 0x87, 0x90, 0x6f, 0x6c, 0xae,
	0x16, 0xed, 0x82, 0xfe, 0x78, 0xcc, 0x35, 0x43, 0x7a, 0x04, 0x6f, 0x23, 0xe7, 0x1e, 0xcf, 0x99,
	0x39, 0xf7, 0x0c, 0x44, 0xad, 0x35, 0x9d, 0x39, 0xed, 0x09, 0x6d, 0xce, 0x50, 0x46, 0x0b, 0xd3,
	0xd4, 0x95, 0x35, 0x39, 0xd9, 0xb7, 0xdc, 0xf1, 0xe9, 0xa7, 0x00, 0xdf, 0x01, 0x39, 0x07, 0xaf,
	0xd6, 0xb1, 0x48, 0x44, 0x16, 0x28, 0xaf, 0xd6, 0x52, 0x82, 0xbf, 0x2c, 0x1b, 0x8c, 0xbd, 0x44,
	0x64, 0x3b, 0x8a, 0xb1, 0x8c, 0x60, 0xd6, 0xbe, 0xeb, 0x78, 0xc6, 0x94, 0x83, 0x32, 0x81, 0xb0,
	0xb2, 0x58, 0x76, 0xa8, 0xef, 0xeb, 0x06, 0x63, 0x3f, 0x11, 0x99, 0xaf, 0xa6, 0x94, 0x53, 0xf4,
	0xad, 0xfe, 0x55, 0x04, 0x83, 0x62, 0x42, 0xa5, 0x17, 0x10, 0x5c, 0x59, 0x6b, 0xac, 0xbb, 0xb2,
	0x32, 0x1a, 0x7f, 0x42, 0x30, 0x96, 0x31, 0x6c, 0x35, 0x48, 0x54, 0x2e, 0xc6, 0x24, 0xe3, 0x98,
	0x9e, 0x41, 0xf8, 0x40, 0x68, 0x15, 0xbe, 0xf6, 0x48, 0xdd, 0x3a, 0xf9, 0xd3, 0x2f, 0x01, 0xbb,
	0x83, 0x87, 0x5a, 0xb3, 0x24, 0x3e, 0x9d, 0xfa, 0xaa, 0x42, 0x22, 0x76, 0x6e, 0xab, 0x71, 0x94,
	0x27, 0x10, 0xa0, 0x0b, 0xc5, 0xfe, 0xb0, 0xd8, 0xcf, 0xff, 0x36, 0x97, 0x73, 0x66, 0x35, 0xa8,
	0xe4, 0xf1, 0xd0, 0x22, 0x57, 0x13, 0x16, 0x7b, 0xab, 0x6a, 0xf7, 0x51, 0xac, 0x29, 0x1e, 0xc1,
	0x77, 0x21, 0xe4, 0x1d, 0xcc, 0xaf, 0xb1, 0xbb, 0xb5, 0xe6, 0xb9, 0x7e, 0xc1, 0xcb, 0x8f, 0x1b,
	0x2d, 0x0f, 0x57, 0x7d, 0x93, 0x15, 0x0f, 0x8e, 0xfe, 0xfb, 0x3d, 0x6c, 0x93, 0x6e, 0x3c, 0x6d,
	0xf2, 0x33, 0x9f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x39, 0x41, 0x48, 0x88, 0xfa, 0x01, 0x00,
	0x00,
}
